# Generated by Django 5.0.3 on 2024-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_attraction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='image',
            field=models.ImageField(blank=True, default='images/1.jpeg', null=True, upload_to='images/'),
        ),
    ]
